FROM registry.access.redhat.com/ubi8/ubi-minimal
WORKDIR /work/
COPY target/*-runner.jar /work/application.jar
RUN chmod 775 /work
EXPOSE 8080
CMD ["./application", \
    "-Dquarkus.http.host=0.0.0.0", \
    "-Dquarkus.http.port=8080", \
    "-Dauth.ms.jwt_server.services.external.TokenStoreService/mp-rest/url=http://token-store:8080" \
]
