FROM adoptopenjdk/openjdk11:ubi-minimal-jre
WORKDIR /work/
COPY target/lib /work/lib
COPY target/*-runner.jar /work/application.jar
ENV JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5007"
RUN chmod 775 /work
EXPOSE 8080
CMD ["java", \
    "-Dquarkus.http.host=0.0.0.0", \
    "-Dquarkus.http.port=8080", \
    "-Dauth.ms.jwt_server.services.external.TokenStoreService/mp-rest/url=http://token-store:8080", \
    "-jar", \
    "./application.jar" \
]