networks:
  custom_net:    
    ipam:
      config:
        - subnet: 172.18.0.0/16
          
services:
  login-server:
    image: login-server
    extra_hosts:
      - "host.docker.internal:172.18.0.6" 
    ports:
      - "8080:8080"
      - "5010:5010"
    depends_on:
      - jwt-server
      - credentials-store
    networks:
      custom_net:
        ipv4_address: 172.18.0.6
  credentials-store:
    image: credentials-store
    expose:
      - "8080"
    ports:      
      - "5006:5006"
    networks:
      custom_net:
        ipv4_address: 172.18.0.7
  token-store:
    image: token-store
    expose:
      - "8080"
    networks:
      custom_net:
        ipv4_address: 172.18.0.8    
  jwt-server:
    image: jwt-server
    expose:
      - "8080"
    ports:      
      - "5007:5007"
    depends_on:
      - token-store
    networks:
      custom_net:
        ipv4_address: 172.18.0.9    
  gateway-service:
    image: gateway-service
    ports:
      - "8086:8086"
      - "5008:5008"
    networks:
      custom_net:
        ipv4_address: 172.18.0.10    
  customer-service:
    image: customer-service
    ports:
      - "8087:8087"
      - "5009:5009"
    networks:
      custom_net:
        ipv4_address: 172.18.0.11     
