version: "3"

services:
  credentials-store:
    image: credentials-store
    expose:
      - "8080"
    ports:      
      - "5006:5006"
  token-store:
    image: token-store
    expose:
      - "8080"
  jwt-server:
    image: jwt-server
    expose:
      - "8080"
    ports:      
      - "5007:5007"
    depends_on:
      - token-store
  login-server:
    image: login-server
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - jwt-server
      - credentials-store
  gateway-service:
    image: gateway-service
    ports:
      - "8086:8086"
      - "5008:5008"
  customer-service:
    image: customer-service
    ports:
      - "8087:8087"
      - "5009:5009"
