FROM adoptopenjdk/openjdk11:ubi-minimal-jre
WORKDIR /work/
COPY target/lib /work/lib
COPY target/*-runner.jar /work/application.jar
ENV JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006"
RUN chmod 775 /work
EXPOSE 8080
EXPOSE 5006
CMD ["java", \
    "-Dquarkus.http.host=0.0.0.0", \
    "-Dquarkus.http.port=8080", \
    "-Dquarkus.datasource.jdbc.url=jdbc:h2:/data/ms-credentials;AUTO_SERVER=TRUE", \
    "-jar", \
    "./application.jar" \
]
