server:
  port: 8086

jwt:
  prefix: r_token

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
auth:
  uri: /api/auth/verify
  baseuri: http://172.18.0.6:8080
customer:
  uri: http://172.18.0.11:8087